"""initial5

Revision ID: 0077507d76a1
Revises: cf4642fba307
Create Date: 2023-06-28 06:11:28.469481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0077507d76a1'
down_revision = 'cf4642fba307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('meesage_sender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'meesage_sender')
    # ### end Alembic commands ###
