"""Initial3

Revision ID: 0d9b052b0d4a
Revises: 18aa1ba66c43
Create Date: 2023-08-26 04:41:45.975935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9b052b0d4a'
down_revision = '18aa1ba66c43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
