"""Initial9

Revision ID: 0df79a664bd7
Revises: af8619603f5d
Create Date: 2023-09-15 03:05:56.138965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df79a664bd7'
down_revision: Union[str, None] = 'af8619603f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_timestamp', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_chats_last_message_timestamp'), 'chats', ['last_message_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_last_message_timestamp'), table_name='chats')
    op.drop_column('chats', 'last_message_timestamp')
    # ### end Alembic commands ###
