"""initial3

Revision ID: 103d4b1afeee
Revises: 5323cb7a5a8b
Create Date: 2023-06-28 05:13:09.485093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103d4b1afeee'
down_revision = '5323cb7a5a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('current_username_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('partner_username_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('date_message', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_messages_date_message'), 'messages', ['date_message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_date_message'), table_name='messages')
    op.drop_column('messages', 'date_message')
    op.drop_column('messages', 'partner_username_id')
    op.drop_column('messages', 'current_username_id')
    # ### end Alembic commands ###
