"""Initial15

Revision ID: 179072970aa5
Revises: cc0257b430cf
Create Date: 2023-09-30 04:54:08.110262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179072970aa5'
down_revision: Union[str, None] = 'cc0257b430cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('owner_username', sa.String(), nullable=True))
    op.add_column('likes', sa.Column('liker_username', sa.String(), nullable=True))
    op.drop_index('ix_likes_username', table_name='likes')
    op.create_index(op.f('ix_likes_liker_username'), 'likes', ['liker_username'], unique=False)
    op.create_index(op.f('ix_likes_owner_username'), 'likes', ['owner_username'], unique=False)
    op.drop_column('likes', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_likes_owner_username'), table_name='likes')
    op.drop_index(op.f('ix_likes_liker_username'), table_name='likes')
    op.create_index('ix_likes_username', 'likes', ['username'], unique=False)
    op.drop_column('likes', 'liker_username')
    op.drop_column('likes', 'owner_username')
    # ### end Alembic commands ###
