"""Initial3

Revision ID: 18aa1ba66c43
Revises: 34a0c0125643
Create Date: 2023-08-26 04:39:09.660791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18aa1ba66c43'
down_revision = '34a0c0125643'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_avatar', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('partner_user_avatar', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_partner_user_avatar'), 'messages', ['partner_user_avatar'], unique=False)
    op.create_index(op.f('ix_messages_user_avatar'), 'messages', ['user_avatar'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_avatar'), table_name='messages')
    op.drop_index(op.f('ix_messages_partner_user_avatar'), table_name='messages')
    op.drop_column('messages', 'partner_user_avatar')
    op.drop_column('messages', 'user_avatar')
    # ### end Alembic commands ###
