"""Initial14

Revision ID: 285326178038
Revises: 8c1f92220bad
Create Date: 2023-09-29 06:26:49.372693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285326178038'
down_revision: Union[str, None] = '8c1f92220bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_pictures_user_id', table_name='pictures')
    op.create_index(op.f('ix_pictures_username'), 'pictures', ['username'], unique=False)
    op.drop_column('pictures', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pictures_username'), table_name='pictures')
    op.create_index('ix_pictures_user_id', 'pictures', ['user_id'], unique=False)
    op.drop_column('pictures', 'username')
    # ### end Alembic commands ###
