"""Initial2

Revision ID: 34a0c0125643
Revises: f21bc243ce88
Create Date: 2023-08-26 01:58:32.572477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a0c0125643'
down_revision = 'f21bc243ce88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
