"""Initial10

Revision ID: 403d8e719a9d
Revises: 697706e75bb0
Create Date: 2023-09-26 02:16:37.226753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403d8e719a9d'
down_revision: Union[str, None] = '697706e75bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headerImg', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_headerImg'), 'users', ['headerImg'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_headerImg'), table_name='users')
    op.drop_column('users', 'headerImg')
    # ### end Alembic commands ###
