"""initial6

Revision ID: 54b8354db7fa
Revises: 0077507d76a1
Create Date: 2023-06-28 07:57:38.995885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b8354db7fa'
down_revision = '0077507d76a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_sender', sa.Integer(), nullable=True))
    op.drop_column('messages', 'meesage_sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('meesage_sender', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'message_sender')
    # ### end Alembic commands ###
