"""Initial10

Revision ID: 697706e75bb0
Revises: 0df79a664bd7
Create Date: 2023-09-16 01:48:00.232362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697706e75bb0'
down_revision: Union[str, None] = '0df79a664bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
