"""Initial7

Revision ID: 828e582cf4b7
Revises: d74b7778c922
Create Date: 2023-09-08 01:58:47.689191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828e582cf4b7'
down_revision: Union[str, None] = 'd74b7778c922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twoAuth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twoAuth')
    # ### end Alembic commands ###
