"""Initial3

Revision ID: 82d85454508a
Revises: 0d9b052b0d4a
Create Date: 2023-08-26 04:43:05.669402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d85454508a'
down_revision = '0d9b052b0d4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
