"""Initial3

Revision ID: af58f3d23c93
Revises: 82d85454508a
Create Date: 2023-08-26 19:11:48.531221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af58f3d23c93'
down_revision = '82d85454508a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_partner_user_avatar', table_name='messages')
    op.drop_index('ix_messages_user_avatar', table_name='messages')
    op.drop_column('messages', 'partner_user_avatar')
    op.drop_column('messages', 'user_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('partner_user_avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_messages_user_avatar', 'messages', ['user_avatar'], unique=False)
    op.create_index('ix_messages_partner_user_avatar', 'messages', ['partner_user_avatar'], unique=False)
    # ### end Alembic commands ###
