"""Initial9

Revision ID: af8619603f5d
Revises: ea8785cc1ad2
Create Date: 2023-09-15 02:21:31.394729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8619603f5d'
down_revision: Union[str, None] = 'ea8785cc1ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message', sa.String(), nullable=True))
    op.create_index(op.f('ix_chats_last_message'), 'chats', ['last_message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_last_message'), table_name='chats')
    op.drop_column('chats', 'last_message')
    # ### end Alembic commands ###
