"""Initial5

Revision ID: bd94e2a33a9a
Revises: c05b0f05451b
Create Date: 2023-09-03 04:59:31.131558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd94e2a33a9a'
down_revision: Union[str, None] = 'c05b0f05451b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_headerImg', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_headerImg', 'users', ['headerImg'], unique=False)
    # ### end Alembic commands ###
