"""initial4

Revision ID: cf4642fba307
Revises: 103d4b1afeee
Create Date: 2023-06-28 05:15:55.951948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4642fba307'
down_revision = '103d4b1afeee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('current_user_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('partner_user_id', sa.Integer(), nullable=True))
    op.drop_column('messages', 'partner_username_id')
    op.drop_column('messages', 'current_username_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('current_username_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('partner_username_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'partner_user_id')
    op.drop_column('messages', 'current_user_id')
    # ### end Alembic commands ###
